# Generated by Django 4.1.6 on 2023-02-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('DNI', models.IntegerField(max_length=10)),
                ('Mail', models.CharField(max_length=30)),
            ],
        ),
    ]
