# Generated by Django 4.1.6 on 2023-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Profesion', models.CharField(max_length=10)),
                ('Mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
    ]
